---
title: training-session
config:
  formCreate: true
  tableFilter: true
  table: true
formCreate:
- title: id
  dataIndex: training-session_id
  key: training-session_id
  valueType: number
  required: false
  width: m
  formItemProps: []
- title: areaId
  dataIndex: training-session_areaid
  key: training-session_areaid
  valueType: number
  required: false
  width: m
  formItemProps: []
- title: name
  dataIndex: training-session_name
  key: training-session_name
  valueType: string
  required: false
  width: m
  formItemProps: []
- title: image
  dataIndex: training-session_image
  key: training-session_image
  valueType: string
  required: false
  width: m
  formItemProps: []
- title: description
  dataIndex: training-session_description
  key: training-session_description
  valueType: string
  required: false
  width: m
  formItemProps: []
- title: published
  dataIndex: training-session_published
  key: training-session_published
  valueType: number
  required: false
  width: m
  formItemProps: []
- title: ""
  dataIndex: training-session_
  key: training-session_
  valueType: string
  required: false
  width: m
  formItemProps: []
tableFilter:
- title: id
  dataIndex: training-session_id
  key: training-session_id
  valueType: number
  required: false
  width: m
  formItemProps: []
- title: areaId
  dataIndex: training-session_areaid
  key: training-session_areaid
  valueType: number
  required: false
  width: m
  formItemProps: []
- title: name
  dataIndex: training-session_name
  key: training-session_name
  valueType: string
  required: false
  width: m
  formItemProps: []
- title: image
  dataIndex: training-session_image
  key: training-session_image
  valueType: string
  required: false
  width: m
  formItemProps: []
- title: description
  dataIndex: training-session_description
  key: training-session_description
  valueType: string
  required: false
  width: m
  formItemProps: []
- title: published
  dataIndex: training-session_published
  key: training-session_published
  valueType: number
  required: false
  width: m
  formItemProps: []
- title: ""
  dataIndex: training-session_
  key: training-session_
  valueType: string
  required: false
  width: m
  formItemProps: []
table:
  data:
  - title: id
    dataIndex: training-session_id
    key: training-session_id
    valueType: number
    required: false
    width: m
    formItemProps: []
  - title: areaId
    dataIndex: training-session_areaid
    key: training-session_areaid
    valueType: number
    required: false
    width: m
    formItemProps: []
  - title: name
    dataIndex: training-session_name
    key: training-session_name
    valueType: string
    required: false
    width: m
    formItemProps: []
  - title: image
    dataIndex: training-session_image
    key: training-session_image
    valueType: string
    required: false
    width: m
    formItemProps: []
  - title: description
    dataIndex: training-session_description
    key: training-session_description
    valueType: string
    required: false
    width: m
    formItemProps: []
  - title: published
    dataIndex: training-session_published
    key: training-session_published
    valueType: number
    required: false
    width: m
    formItemProps: []
  - title: ""
    dataIndex: training-session_
    key: training-session_
    valueType: string
    required: false
    width: m
    formItemProps: []
  total: 7
  success: true
...
