---
title: training-unit
config:
  formCreate: true
  tableFilter: true
  table: true
formCreate:
- title: id
  dataIndex: training-unit_id
  key: training-unit_id
  valueType: number
  required: false
  width: m
  formItemProps: []
- title: tsId
  dataIndex: training-unit_tsid
  key: training-unit_tsid
  valueType: number
  required: false
  width: m
  formItemProps: []
- title: name
  dataIndex: training-unit_name
  key: training-unit_name
  valueType: string
  required: false
  width: m
  formItemProps: []
- title: image
  dataIndex: training-unit_image
  key: training-unit_image
  valueType: string
  required: false
  width: m
  formItemProps: []
- title: description
  dataIndex: training-unit_description
  key: training-unit_description
  valueType: string
  required: false
  width: m
  formItemProps: []
- title: tsSeq
  dataIndex: training-unit_tsseq
  key: training-unit_tsseq
  valueType: number
  required: false
  width: m
  formItemProps: []
- title: published
  dataIndex: training-unit_published
  key: training-unit_published
  valueType: number
  required: false
  width: m
  formItemProps: []
- title: ""
  dataIndex: training-unit_
  key: training-unit_
  valueType: string
  required: false
  width: m
  formItemProps: []
tableFilter:
- title: id
  dataIndex: training-unit_id
  key: training-unit_id
  valueType: number
  required: false
  width: m
  formItemProps: []
- title: tsId
  dataIndex: training-unit_tsid
  key: training-unit_tsid
  valueType: number
  required: false
  width: m
  formItemProps: []
- title: name
  dataIndex: training-unit_name
  key: training-unit_name
  valueType: string
  required: false
  width: m
  formItemProps: []
- title: image
  dataIndex: training-unit_image
  key: training-unit_image
  valueType: string
  required: false
  width: m
  formItemProps: []
- title: description
  dataIndex: training-unit_description
  key: training-unit_description
  valueType: string
  required: false
  width: m
  formItemProps: []
- title: tsSeq
  dataIndex: training-unit_tsseq
  key: training-unit_tsseq
  valueType: number
  required: false
  width: m
  formItemProps: []
- title: published
  dataIndex: training-unit_published
  key: training-unit_published
  valueType: number
  required: false
  width: m
  formItemProps: []
- title: ""
  dataIndex: training-unit_
  key: training-unit_
  valueType: string
  required: false
  width: m
  formItemProps: []
table:
  data:
  - title: id
    dataIndex: training-unit_id
    key: training-unit_id
    valueType: number
    required: false
    width: m
    formItemProps: []
  - title: tsId
    dataIndex: training-unit_tsid
    key: training-unit_tsid
    valueType: number
    required: false
    width: m
    formItemProps: []
  - title: name
    dataIndex: training-unit_name
    key: training-unit_name
    valueType: string
    required: false
    width: m
    formItemProps: []
  - title: image
    dataIndex: training-unit_image
    key: training-unit_image
    valueType: string
    required: false
    width: m
    formItemProps: []
  - title: description
    dataIndex: training-unit_description
    key: training-unit_description
    valueType: string
    required: false
    width: m
    formItemProps: []
  - title: tsSeq
    dataIndex: training-unit_tsseq
    key: training-unit_tsseq
    valueType: number
    required: false
    width: m
    formItemProps: []
  - title: published
    dataIndex: training-unit_published
    key: training-unit_published
    valueType: number
    required: false
    width: m
    formItemProps: []
  - title: ""
    dataIndex: training-unit_
    key: training-unit_
    valueType: string
    required: false
    width: m
    formItemProps: []
  total: 8
  success: true
...
